### ISSUE TITLE
Grpc Web

### ISSUE THREAD

**Issue by gedw99** [terrier989/universal_io#1]
Have you tested if your fork supports grpc web inside a web browser ? I always thought the lack of frames support prevented this

**Comment by terrier989** [comment]
Package _grpc_ uses [http2](https://pub.dev/packages/http2), which implements HTTP/2 on top of bidirectional streams (normally TCP sockets). To run _grpc_ in the web, you would need to implement some way of bidirectional streaming (for example, on top of Websockets).
